add util functions
ozoncp/ocp-knowledge-api pull request #2
Opened 2021-07-19 16:08 UTC by eugene-sh

2021-07-19 20:49 UTC, kshmatov requested changes

2021-07-19 20:49 UTC, kshmatov commented on internal/utils/utils.go
> +	if inSize < batchSize {
Не уверен, что стоит возвращать ошибку. Можно вернуть слайс с одним элементом, который полностью включает в себя исходный слайс. Т.е. 
BatchSlice([]int{1, 2, 3},  9) => [][]int{ []int{1, 2, 3}, }

2021-07-19 20:49 UTC, kshmatov commented on internal/utils/utils.go
> +	batchCount := (inSize / batchSize) + 1
Вот здесь при большом размере batchSize будет впустую теряться память в некоторых случаях. При указании капасити и длины, make будет резервировать непрерывную область памяти в которую влезет вся длина, независимо от итого будет она потом заполнена или нет, т.е. будет создан массив размера cap на который отражается слайс с текущей длиной len. Это позволяет избежать лишних переаллокаций при добавлении элементов. Но если добавить меньше, то память все равно считается занятой и не выделяется другим переменным.
При inSize = 9, batchSize = 3 получим bathcCount = 4, т.е. один элемент лишний. Для размера слайса 3  это некритично, но если мы сделаем размер 1к или 10к может оказаться уже не так жизнерадостно, особенно если эта функция будет вызываться в каком-нибудь цикле.

2021-07-19 20:49 UTC, kshmatov commented on internal/utils/utils_test.go
> +	var testCases = []struct {
Нет проверок ошибочных случаев.

2021-07-19 21:16 UTC, kshmatov commented on internal/utils/utils_test.go
> +	var testCases = []struct {
И забыл. Если после деления слайса в исходном поменять значение какого нибудь элемента, то в полученном результате тоже будут изменения.
a := []int{1, 2, 3}
res, _ := BatchSlice(a, 1)
a[0] = 10
res[0][0] - ?

2021-07-20 08:02 UTC, eugene-sh commented on internal/utils/utils.go
> +	if inSize < batchSize {
Шото не подумав вписал такое. Поправил

2021-07-20 08:22 UTC, eugene-sh commented on internal/utils/utils.go
> +	batchCount := (inSize / batchSize) + 1
на сколько я понимаю, независимо от размера входного слайса у нас в худжем случае будет зарезервирован 1 лишний элемент. Это не значит что мы резервируем память под весь батч. В этой строке batchedSlice := make([][]int, 0, batchCount) мы резервуируем место ток под слайс для батчей.

2021-07-20 08:22 UTC, eugene-sh commented on internal/utils/utils_test.go
> +	var testCases = []struct {
На сколько я понимаю, тему тестов мы ещё не проходили и на них можно не обращаться внимание.  Написал что бы проверить что всё работает.

Второе замечание поправил.

2021-07-20 16:30 UTC, kshmatov approved these changes

2021-07-20 16:38 UTC, merged